### ISSUE TITLE
Errors after Download

### ISSUE THREAD

**Issue by ZiadAli** [lyft/Kronos#13]
Is the most recent commit a working version of Kronos? I downloaded the pods but all of the Swift files have errors in them.

**Comment by Reflejo** [comment]
What errors do you see? Are you using Swift 3?

**Comment by ZiadAli** [comment]
<img width="259" alt="screen shot 2016-12-01 at 3 10 53 am" src="https://cloud.githubusercontent.com/assets/14086156/20786387/cf67eb38-b773-11e6-8300-8dd659e9d36a.png">

These are some of the errors and yes I'm using Swift 3 and the most recent stable version of Xcode.

**Comment by Reflejo** [comment]
How are you using it? Can you post your `Podfile`?

**Comment by ZiadAli** [comment]
target 'MusicSync' do
  use_frameworks!

pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Kronos'

end

**Comment by Reflejo** [comment]
Try doing 
```bash
$ pod repo update
$ pod update Kronos
```

**Comment by ZiadAli** [comment]
That worked! Thanks for your help!
