### ISSUE TITLE
App Restarts and Network unavailable

### ISSUE THREAD

**Issue by otymartin** [lyft/Kronos#17]
@Reflejo 

How does this behave when a network is not present, is slow or fails to complete request or user restarts app with no network.

Does `clock.now` go out of sync and become unreliable?

**Comment by Reflejo** [comment]
`Clock.sync` actually syncs the clock once and only once every time it's called. So once you sync'ed with an ntp server the NTP clock (i.e. `Clock.now`) will tick independently of the local clock (this is: modifications on the clock will not affect `Clock.now`).

If you restart the app and try to access `Clock.now` before syncing, it'll return `nil`. So the guarantee that you have is that every time `Clock.now` is not `nil` then the time is trustfully

**Comment by otymartin** [comment]
@Reflejo Hey so in a situation where the app launches with no network but network returns during use. Do I have to manually call Clock.sync or will it automatically sync?

**Comment by Reflejo** [comment]
@otymartin you need to call `Clock.sync` again after the network is reachable.

**Comment by otymartin** [comment]
@Reflejo thanks for the fast help :)

**Comment by Reflejo** [comment]
yw

**Comment by acecilia** [comment]
Related with the initial question.
If you start the app and never call `Clock.sync`, will `Clock.now` always be `nil`, or does it auto-sync at some point?
Thanks
