### ISSUE TITLE
Calling sync() from a background thread does not work

### ISSUE THREAD

**Issue by jordansmithnz** [lyft/Kronos#25]
Calling sync() from a background thread does not seem to work - neither the first or full completion handlers ever get called, not even after the timeout duration. Running the call from the main thread resolves the issue.

Might be worth documenting, or handling a little better?

**Comment by Reflejo** [comment]
Wanna take a stab at fixing it ? :)

**Comment by jordansmithnz** [comment]
Sure - just opened a pull request

**Comment by AndrewSB** [comment]
was this fixed? can I call from a background thread?

**Comment by AndrewSB** [comment]
assuming it was, I see https://github.com/MobileNativeFoundation/Kronos/pull/29/files was merged
