### ISSUE TITLE
Not working for certain NTP server

### ISSUE THREAD

**Issue by qinglintian** [lyft/Kronos#43]
I have tried setting up NTP server on a Windows PC (WinPC) and a Raspberry Pi (RPi) and noticed that the framework works well syncing time with WinPC but fail to do so when setting RPi as the server. 

I simply run "Clock.sync(from: (IP of WinPC/RPi))" during initialization of the app and use "Clock.now" to get server time. When setting the IP of WinPC, it works, while setting IP of RPi doesn't.

The way I set up NTP server on RPi is by adding following lines to /etc/ntp.conf
`server 127.127.1.0`
`fudge 127.127.1.0 stratum 10`

`restrict 192.168.0.24 mask 255.255.255.0 nomodify`

I have tested on a Macbook Pro with command "ntpdate -u (IP of RPi)" to sync time from RPi and it works well, which proves that the NTP server on RPi is running.

I would appreciate if you could provide any help/comment on this issue. Thank you.

**Comment by Reflejo** [comment]
Can you try debugging a bit more where the problem is? Is your server using ntp v3?

**Comment by Reflejo** [comment]
Is this still an issue? Please reopen if so
