### ISSUE TITLE
Not available as CocoaPod

### ISSUE THREAD

**Issue by ashevin** [lyft/Kronos#5]
It does not appear that the podspec has been submitted to the Cocoapods repo.

**Comment by Reflejo** [comment]
Thanks for the heads up. Just uploaded it.

**Comment by Reflejo** [comment]
I just bumped the version to 0.1.2 make sure to run `pod repo update` before trying it, and please let me know if you have any other problem

**Comment by ashevin** [comment]
Your response was very _time_ly. :-)

All good here.
