### ISSUE TITLE
Kronos not working on cellular data but only on Wifi?

### ISSUE THREAD

**Issue by agforte** [lyft/Kronos#52]
It looks like Clock.sync() does not work if I have WiFi off and cellular data (LTE) on. In particular, the "first:" and "completion:" blocks never get called. It works if WiFi is on.
Am I missing something? It seems rather odd.

**Comment by Reflejo** [comment]
It definitely should work on cellular. We use it at lyft on production. Can you debug a bit more your case and provide more information about where it breaks?

**Comment by agforte** [comment]
So, I have found out the following:

If I use an NTP pool with just one entry: "0.pool.ntp.org" then everything works as expected.
If I use an NTP pool with more than one entry: "time.apple.com 0.pool.ntp.org" then it works only on WiFi and only the completion block gets called (not the "first" block)

Any ideas?

**Comment by aklowther** [comment]
@agforte is this still an issue?  It would definitely prevent me from using this framework in my project

**Comment by Reflejo** [comment]
This is not an issue. We had been running Kronos in production at Lyft for
a long time now

**Comment by keith** [comment]
Feel free to submit a new issue with more specifics if you're still seeing this!
