### ISSUE TITLE
Update logs with accurate time 

### ISSUE THREAD

**Issue by AndrewSB** [lyft/Kronos#6]
When my app is launched, I want to create a
```
struct Log {
    ...
    let ts: Date
    ... 
}
```

and also create them periodically onwards, stored to a file that gets uploaded to a server every couple minutes.

If I use Kronos, I understand the time I initially get will be not be accurate, so the first x logs created will have inaccurate time, is there a straightforward way to update the logs with a more accurate time after the `Clock.sync` callbacks all call back?

**Comment by Reflejo** [comment]
The first time you get will be the less accurate date but for many uses that's "accurate enough". Meaning that it's still sync'ed against an NTP server but if the latency of the connection is not symmetric then the resulting date can have a few milliseconds off.

Having said that `Clock.sync` has a second closure (`complete`) that will be called after all the NTP requests are sent. That's the closure you should use to get the most accurate time.

**Comment by Reflejo** [comment]
Let me know if you have any further questions/concerns

**Comment by AndrewSB** [comment]
Will do! Thank you for the detailed answer @Reflejo 🙃
