### ISSUE TITLE
Swift 3 compatibility?

### ISSUE THREAD

**Issue by gvarela** [lyft/Kronos#7]
Just checking in on whether anyone is tackling or not. Happy to help.

**Comment by Reflejo** [comment]
If you want/can start with the initial implementation of swift 3 that'd be awesome. I'd be curious to see if there are new C wrappers for the stuff Kronos is using that would make the C calls less complex?

**Comment by dduan** [comment]
@gvarela checkout the `swift-3.0` branch 😉

**Comment by keith** [comment]
This is in master as well now.

**Comment by gvarela** [comment]
Awesome Thanks for the contributions!

-- 
Gabe Varela
Sent with Airmail

On October 5, 2016 at 12:41:48 PM, Keith Smiley (notifications@github.com) wrote:

This is in master as well now.
