### ISSUE TITLE
Kronos warning for not being Swift 5

### ISSUE THREAD

**Issue by lucasderraugh** [lyft/Kronos#70]
Because the version was bumped on the Podspec after 4.0.1 was released, the 4.0.1 tag doesn't contain that bump and so Xcode warns that Kronos needs to be converted. Either the tag should be updated to point to commit 5b05b5c00bb742905508267358c4338e538ac64e or a new tag and Podspec bump should be done.

<img width="776" alt="Screen Shot 2020-08-04 at 11 27 38 PM" src="https://user-images.githubusercontent.com/714282/89368665-18f95800-d6aa-11ea-973c-cc6e6e51fcd0.png">

**Comment by keith** [comment]
Released 4.1.0, thanks for the report!

**Comment by lucasderraugh** [comment]
@Keith This actually is still an issue, I think we need to specify `s.swift_versions = ['5.0', '5.2']`. I base this off of other packages that don't give me this warning.

**Comment by keith** [comment]
pushed 4.1.1 with that change. lmk if it doesn't work.

**Comment by lucasderraugh** [comment]
@Keith Perfect, that fixed it.
